export const ArmorEnum = {
  Naked: 0,
  LeatherThong: 1,
  Tunic: 2,
  LegsLeatherArmor: 3,
  LeatherArmorWithoutHelm: 4,
  FullLeatherArmor: 5,
  LegsChainmail: 6,
  ChainmailWithoutHelm: 7,
  FullChainmail: 8,
  LegsScalesArmor: 9,
  ScalesArmorWithoutHelm: 10,
  FullScalesArmor: 11,
  LegsBronzeArmor: 12,
  BronzeArmorWithourHelm: 13,
  FullBronzeArmor: 14,
  LegsPlateArmor: 15,
  PlateArmorWithoutHelm: 16,
  FullPlateArmor: 17
}
